###**PROBLEM 1**

In [117]:
import numpy as np

In [118]:
X = np.random.random((5, 5))  
X


array([[0.81353853, 0.51891091, 0.03396946, 0.24048422, 0.18137931],
       [0.6855394 , 0.39188864, 0.20850232, 0.83790664, 0.13010398],
       [0.39983964, 0.6565539 , 0.69724944, 0.5219916 , 0.9932116 ],
       [0.00099892, 0.4665787 , 0.42475511, 0.54956353, 0.22598447],
       [0.4701801 , 0.78504456, 0.23000515, 0.17209854, 0.33382932]])

In [119]:
mean = X.mean()
mean
print("Mean of X:", mean)

Mean of X: 0.4388043195475271


In [120]:
std = X.std()
std
print("Standard Deviation of X:", std)

Standard Deviation of X: 0.2618290878743139


In [121]:
X_normalized = (X - mean) / std
X_normalized
print("\nNormalized Array:\n", X_normalized)


Normalized Array:
 [[ 1.43121688  0.30594991 -1.54617985 -0.75744106 -0.98317955]
 [ 0.94235168 -0.17918436 -0.87958904  1.52428564 -1.1790147 ]
 [-0.14881723  0.83164777  0.98707567  0.31771597  2.1174396 ]
 [-1.67210375  0.1060783  -0.05365793  0.42302103 -0.81281973]
 [ 0.11983304  1.32239027 -0.79746362 -1.01862547 -0.40092948]]


In [122]:
np.save('X_normalized.npy', X_normalized)

###**PROBLEM 2**

In [123]:
numbers = np.arange(1, 101)
numbers
Arranged_Set = numbers.reshape(10,10)
print("10x10 Array of first 100 Integers:\n", Arranged_Set)

10x10 Array of first 100 Integers:
 [[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [124]:
squares = numbers ** 2
squares
A = squares.reshape(10, 10)
print("10x10 Array of firstSquares:\n", A)

10x10 Array of firstSquares:
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


In [125]:
div_by_3 = A[A % 3 == 0]
print("\nNumbers divisible by 3:\n", div_by_3)


Numbers divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]


In [126]:
np.save('div_by_3.npy', div_by_3)