###**PROBLEM 1**

In [153]:
import numpy as np

In [154]:
X = np.random.random((5, 5))  
X


array([[0.38041874, 0.5082779 , 0.26620679, 0.17111469, 0.14527191],
       [0.81520341, 0.50532503, 0.71667717, 0.86300825, 0.99017651],
       [0.54033978, 0.07086539, 0.45879241, 0.08486953, 0.28358058],
       [0.34801468, 0.03280862, 0.55348193, 0.64047086, 0.37375505],
       [0.75852164, 0.89201533, 0.67570734, 0.72987606, 0.20528742]])

In [155]:
mean = X.mean()
mean
print("Mean of X:", mean)

Mean of X: 0.4804026815678788


In [156]:
std = X.std()
std
print("Standard Deviation of X:", std)

Standard Deviation of X: 0.2749133150349497


In [157]:
X_normalized = (X - mean) / std
X_normalized
print("\nNormalized Array:\n", X_normalized)


Normalized Array:
 [[-0.3636926   0.10139641 -0.77913977 -1.12503825 -1.21904162]
 [ 1.21784106  0.09065531  0.85945088  1.39173167  1.85430753]
 [ 0.21802183 -1.48969609 -0.07860758 -1.43875589 -0.71594239]
 [-0.48156272 -1.62812797  0.26582652  0.58224964 -0.38793185]
 [ 1.01166056  1.49724524  0.71042269  0.90746198 -1.00073457]]


In [158]:
np.save('X_normalized.npy', X_normalized)

In [159]:
loaded = np.load("X_normalized.npy")

###**PROBLEM 2**

In [160]:
numbers = np.arange(1, 101)
numbers
Arranged_Set = numbers.reshape(10,10)
print("10x10 Array of first 100 Integers:\n", Arranged_Set)

10x10 Array of first 100 Integers:
 [[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [161]:
squares = numbers ** 2
squares
A = squares.reshape(10, 10)
print("10x10 Array of firstSquares:\n", A)

10x10 Array of firstSquares:
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


In [162]:
div_by_3 = A[A % 3 == 0]
print("\nNumbers divisible by 3:\n", div_by_3)


Numbers divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]


In [163]:
np.save("div_by_3.npy", div_by_3)

In [164]:
loaded = np.load("div_by_3.npy")